name: Build-Test-Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-path: ${{ steps.build.outputs.path }}
    steps:
      - uses: actions/checkout@v4
      - id: build
        name: Build
        run: |
          mkdir dist && echo "artifact" > dist/app.txt
          echo "path=dist" >> $GITHUB_OUTPUT

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull artifact
        run: echo "Using artifact at ${{ needs.build.outputs.artifact-path }}"
      - name: Test
        run: echo "tests passed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying ${{ needs.build.outputs.artifact-path }}"
